### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/auth/test
Content-Type: application/json

{
  "email": "kaan@test.com",
  "username": "Kaan",
  "password": "123456"
}
###
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "kaan@test.com",
  "password": "123456"
}